version: "3"
services:
  sedes:
    build: "./sedes-service"
    ports:
      - "3001:3000"
  profesores:
    build: "./profesor-service"
    ports:
      - "3002:3000"
  horarios:
    build: "./horario-service"
    ports:
      - "3003:3000"
  talleres:
    build: "./taller-service"
    ports: 
      - "3004:3000"
  alumnos:
    build: "./alumnos-service"
    ports:
      - "3005:3000"

 
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sedes
      - profesores
      - horarios
      - talleres
      - alumnos
